# Vectorization
Vectorization improves the time used in the computation of mathematical operations

In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)


tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version: "+ str(1000*(toc-tic))+" ms")

c = 0
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc = time.time()
print(c)
print("For Loop version: "+ str(1000*(toc-tic))+" ms")


249922.27093090024
Vectorized version: 14.077901840209961 ms
249922.2709309095
For Loop version: 1202.0714282989502 ms


Lets vectorize the following example:
$$
u = Av \\
u_i = \sum_j  A_{ij}v_j
$$

In [15]:
A = np.array([[1,7,3],
              [1,8,3]])
v = np.array([2,2,-5])
u = np.dot(A,v)
print(u)

[1 3]


Now lets apply the exponential to a vector:

$$
v = \begin{bmatrix}
v_1 \\
v_2 \\
\vdots \\
v_n \\
\end{bmatrix} =>
e^v = \begin{bmatrix}
e^{v_1} \\
e^{v_2} \\
\vdots \\
e^{v_n} \\
\end{bmatrix}
$$

In [17]:
import math

v = np.array([2,2,-5])

tic = time.time()
u = np.zeros((3,1))
for i in range(3):
    u[i] = math.exp(v[i])

toc = time.time()

print(u)
print("Vectorized version: "+ str(1000*(toc-tic))+" ms")


u = np.zeros((3,1))
tic = time.time()
u = np.exp(v)
toc = time.time()
print(u)
print("For Loop version: "+ str(1000*(toc-tic))+" ms")


[[7.3890561e+00]
 [7.3890561e+00]
 [6.7379470e-03]]
Vectorized version: 0.5767345428466797 ms
[7.3890561e+00 7.3890561e+00 6.7379470e-03]
For Loop version: 0.1125335693359375 ms


Other example:

$$
\begin{array}{c|cccc}
    & \text{Apples} & \text{Beef} & \text{Eggs} & \text{Potatoes} \\ \hline
\text{Carb} & 56.0 & 0.0 & 4.4 & 68.0 \\
\text{Protein} & 1.2 & 104.0 & 52.0 & 8.0 \\
\text{Fat} & 1.8 & 135.0 & 99.0 & 0.9
\end{array}
$$

In [24]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
                [1.2, 104.0, 52.0, 8.0],
                [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [25]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [26]:
percentage = 100 * A / cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Gradient Descent implementation

$ J \equiv \frac{1}{m} \sum L(a,y) \\
W \in \mathcal{R}^{n_x,m} \\
b \in \mathcal{R} \\
X \in \mathcal{R}^{n_x , m}.$

$L = - (y log(a) + (1-y) log(1-a))$

Logistic regression:

$$
\left\{\begin{matrix}
z^{(1)} = w^T x*{(1)} + b & & z^{(2)} = w^T x*{(2)} + b & & z^{(3)} = w^T x*{(3)} + b \\
a^{(1)} = \sigma (z^{(1)})& & a^{(2)} = \sigma (z^{(2)})& & a^{(3)} = \sigma (z^{(3)})\\ 
\end{matrix}\right.
$$

where
$$
\begin{matrix}
[z^{(1)} & z^{(2)} & \dots & z^{(m)}] & = &  w^T X + [b,b, \dots ,b] & = & w^T x^{(1)} + b + &\dots&  + w^T x^{(m)} + b
\end{matrix}
$$
this may be `z = np.dot(w.T ,X) + b` and `a=np.sigmoid(z)`

In [18]:
# Logistic regression with for loop

# J = 0, dw1 = 0,dw2 = 0, db = 0
# for i in range(1,m):
    # z[i] = w.T*x[i] +b
    # a[i] = np.sigmoid(z[i])
    # J+= - [ y[i] * np.log(a[i]) + (1-y[i]) * np.log(1-a[i])]
    # 
    # dz[i] = a[i] - y[i]
    # dw1[i] = x1[i]*dz[i]
    # dw2[i] = x2[i]*dz[i]
    # db += dz[i]
# J = J/m
# dw1 = dw1/m
# dw2 = dw2/m
# db = db/m

In [ ]:
Z = np.dot(w.T,x) + b
A = np.sigmoid(Z)
dZ = A -Y
dw = 1/m * X * dZ.T
db = 1/m * np.sum(dZ)

